Add content to working mode page
w3c/did-wg pull request #9
Opened 2019-10-01 21:20 UTC by brentzundel

Working mode: line length, link fixes, minor edits, added content from 01-10-19 meeting

The changes will be more easily reviewed using `rich diff` rather than `source diff`

Signed-off-by: Brent <brent.zundel@gmail.com>

2019-10-01 22:40 UTC, burnburn requested changes
I may suggest some other changes later via separate PR to keep things simple (and get this merged), but this is fine after my one comment is addressed.

2019-10-01 22:40 UTC, burnburn commented on WorkMode/guiding_principles.md
> +    not precise enough.
Not clear which 1.0 this is referencing.  Perhaps drop the final sentence?

2019-10-01 22:54 UTC, brentzundel commented on WorkMode/guiding_principles.md
> +    it is appropriate to be silent. Several issues have arisen on both
```suggestion
    it is appropriate to be silent.
```

2019-10-01 22:54 UTC, brentzundel commented on WorkMode/guiding_principles.md
> +    sides -- sometimes 1.0 is too prescriptive, sometimes the definition is
```suggestion
```

2019-10-01 22:54 UTC, brentzundel commented on WorkMode/guiding_principles.md
> +    not precise enough.
```suggestion
```

2019-10-02 17:08 UTC, brentzundel commented
@burnburn I removed the sentence.

2019-10-09 14:00 UTC, brentzundel commented
@burnburn I would really like to get this merged. Are there any additional changes you see are needed?

2019-10-09 21:10 UTC, TallTed commented on WorkMode/guiding_principles.md
> +the group are encouraged to edit (e.g. to update, correct, etc.) the
```suggestion
the group are encouraged to edit (e.g., to update, correct, etc.) the
```

2019-10-09 21:12 UTC, TallTed commented on WorkMode/guiding_principles.md
> +* Any independent organization, group or individual can be a supporter,
```suggestion
* Any independent organization, group, or individual can be a supporter,
```

2019-10-09 21:12 UTC, TallTed commented on WorkMode/guiding_principles.md
> +    regardless of whether they are part of the Working Group, or members of
```suggestion
    regardless of whether they are part of the Working Group, or a member of
```

2019-10-09 21:13 UTC, TallTed commented on WorkMode/guiding_principles.md
> +A simpler solution (to understand, implement and use) is better than a more
```suggestion
A solution that is simpler (to understand, implement, and use) is better than a more
```

2019-10-09 21:16 UTC, TallTed commented on WorkMode/index.md
> +the group are encouraged to edit (e.g. to update, correct, etc.) the
```suggestion
the group are encouraged to edit (e.g., to update, correct, etc.) the
```

2019-10-09 21:17 UTC, TallTed commented on WorkMode/index.md
> +Participation from the Public (i.e., non group members), via our Public
```suggestion
Participation from the Public (i.e., non group members) via our Public
```

2019-10-09 21:54 UTC, TallTed commented on WorkMode/index.md
> +    from one week to 10 working days, depending on the chair's evaluation
```suggestion
    from 5 to 10 working days, depending on the chair's evaluation
```

2019-10-09 21:56 UTC, TallTed commented on WorkMode/index.md
> +For the minutes, resolutions, and consensus achieved at the f2f meetings
```suggestion
For the minutes, resolutions, and consensus achieved at the f2f meetings,
```

2019-10-09 21:58 UTC, TallTed commented on WorkMode/index.md
> +read the mailing list archives, or watch the github issues. They can also
```suggestion
reading the mailing list archives, or watching the github issues. They can also
```

2019-10-09 21:59 UTC, TallTed commented on WorkMode/index.md
> +raise issues on github and the Working Group is required to answer to those
```suggestion
raise issues on github, which the Working Group is required to answer
```
(+ the following deletion of `issues`)

2019-10-09 22:00 UTC, TallTed commented on WorkMode/index.md
> +issues within a reasonable time. The chairs of the Working Group may also
(along with the above line-edit, deleting `to those`)
```suggestion
within a reasonable time. The chairs of the Working Group may also
```

2019-10-09 22:01 UTC, TallTed commented on WorkMode/index.md
> +contributions, or attempt to influence an approach to a feature that may
```suggestion
contributions, nor attempt to influence an approach to a feature, that may
```

2019-10-09 22:02 UTC, TallTed commented on WorkMode/index.md
> +very seriously, and any attempt to work-around these basic requirements
```suggestion
very seriously, and any attempt to work around these basic requirements
```

2019-10-09 22:04 UTC, TallTed commented on WorkMode/index.md
> +grammatical or stylistic changes), albeit they can choose to do that
```suggestion
grammatical, or stylistic changes), albeit they can choose to do that
```

2019-10-09 22:04 UTC, TallTed commented on WorkMode/index.md
> +directly on the core repository.
```suggestion
directly on the core repository (i.e., without creating a distinct fork).
```

2019-10-09 22:05 UTC, TallTed commented on WorkMode/index.md
> +week. If no objection is raised during that time the issue can be closed or
```suggestion
week. If no objection is raised during that time, the issue can be closed or
```

2019-10-09 22:05 UTC, TallTed commented on WorkMode/index.md
> +GitHub issues are also used as a records of wide reviews, of horizontal
```suggestion
GitHub issues are also used as a record of wide reviews, of horizontal
```

2019-10-09 22:08 UTC, TallTed commented on WorkMode/index.md
> +final arbiters of any process question, however the Working Group has
```suggestion
final arbiters of any process question; however, the Working Group has
```

2019-10-09 22:09 UTC, TallTed commented on WorkMode/index.md
> +    of the [DID Specification](https://github.com/w3c/did-spec) will be
```suggestion
    of the [DID Specification](https://github.com/w3c/did-spec) be
```

2019-10-09 22:13 UTC, TallTed commented on WorkMode/newbie.md
> +team” (in GitHub‘s jargon). That would give you the possibility of being
```suggestion
team” (in GitHub‘s jargon). That would enable you to be
```

2019-10-09 22:14 UTC, TallTed commented on WorkMode/newbie.md
> +your preferred IRC nickname (or nicknames, if you use several of those).**
```suggestion
your preferred IRC nickname(s).**
```

2019-10-09 22:15 UTC, TallTed commented on WorkMode/newbie.md
> +minutes. Actually, in case you are already a seasoned GitHub user: the
```suggestion
minutes. If you are already a seasoned GitHub user: the
```

2019-10-09 22:16 UTC, TallTed commented on WorkMode/newbie.md
> +nicknames are stored (of course:-) in a
```suggestion
IRC and GitHub nicknames are stored (of course :-) ) in a
```

2019-10-09 22:17 UTC, TallTed commented on WorkMode/newbie.md
> +any time* — if you have any questions, issues, concerns, etc. about the
```suggestion
any time* — if you have any questions, issues, concerns, etc., about the
```

2019-10-09 22:18 UTC, TallTed commented on WorkMode/newbie.md
> +available which takes little over an hour and a half to complete.
```suggestion
available which typically takes about 90 minutes to complete.
```

2019-10-09 22:20 UTC, TallTed commented
I didn't realize there would be so many, or I would have made a more consolidated review.

2019-10-10 04:48 UTC, iherman commented
Wow, @TallTed :-) Thanks!

2019-10-10 17:24 UTC, brentzundel commented on WorkMode/index.md
> +contributions, or attempt to influence an approach to a feature that may
```suggestion
contributions, nor attempt to influence an approach, to a feature that may
```

2019-10-15 20:38 UTC, brentzundel commented
> I didn't realize there would be so many, or I would have made a more consolidated review.

@TallTed fwiw, I really appreciated the use of `suggestion mode`
It makes your recommendations really easy to merge.

2019-10-17 10:01 UTC, burnburn approved these changes

2019-10-17 10:02 UTC, merged